"""Unit tests for WAF fingerprint detectors — all tests use mock responses."""
from __future__ import annotations
import pytest
from unittest.mock import MagicMock
from core.models import WAFVendor
from core.fingerprints.cloudflare  import CloudflareDetector
from core.fingerprints.akamai      import AkamaiDetector
from core.fingerprints.modsecurity import ModSecurityDetector
from core.fingerprints.aws_waf     import AWSWAFDetector
from core.fingerprints.imperva     import ImpervaDetector
from core.fingerprints.f5_bigip    import F5BigIPDetector
from core.classifiers.orchestrator import FingerprintOrchestrator, CONFIDENCE_THRESHOLD


def _mock_response(headers: dict, status: int = 200,
                   body: str = "", cookies: dict | None = None):
    r = MagicMock()
    r.headers    = headers
    r.status_code = status
    r.cookies    = cookies or {}
    r.content    = body.encode()
    r.text       = body
    return r


# ── Cloudflare ────────────────────────────────────────────────────────────────

class TestCloudflareDetector:
    def setup_method(self):
        self.det = CloudflareDetector()

    def test_cf_ray_header_detected(self):
        r = _mock_response({"cf-ray": "8abc-LHR", "server": "cloudflare"})
        result = self.det.score(r, "")
        assert result.vendor == WAFVendor.CLOUDFLARE
        assert result.confidence >= CONFIDENCE_THRESHOLD

    def test_cf_cache_status(self):
        r = _mock_response({"cf-cache-status": "MISS"})
        result = self.det.score(r, "")
        assert result.confidence >= 0.20

    def test_block_body_pattern(self):
        body = "Attention Required! | Cloudflare  Ray ID: 7abc1234def56789"
        r = _mock_response({}, 403, body)
        result = self.det.score(r, body)
        assert result.confidence >= CONFIDENCE_THRESHOLD

    def test_no_signals_zero_confidence(self):
        r = _mock_response({"server": "nginx"})
        result = self.det.score(r, "Hello world")
        assert result.confidence == 0.0

    def test_cf_cookie(self):
        r = _mock_response({}, cookies={"cf_clearance": "abc123"})
        result = self.det.score(r, "")
        assert result.confidence >= 0.20


# ── Akamai ────────────────────────────────────────────────────────────────────

class TestAkamaiDetector:
    def setup_method(self):
        self.det = AkamaiDetector()

    def test_akamai_request_id(self):
        r = _mock_response({"x-akamai-request-id": "12345"})
        result = self.det.score(r, "")
        assert result.vendor == WAFVendor.AKAMAI
        assert result.confidence >= CONFIDENCE_THRESHOLD

    def test_bm_cookie(self):
        r = _mock_response({}, cookies={"ak_bmsc": "xyz"})
        result = self.det.score(r, "")
        assert result.confidence >= 0.30

    def test_body_pattern(self):
        body = "Access Denied by Akamai. Reference # 18.12345678.1234567890.abcdef"
        r = _mock_response({}, 403, body)
        result = self.det.score(r, body)
        assert result.confidence >= CONFIDENCE_THRESHOLD


# ── ModSecurity ───────────────────────────────────────────────────────────────

class TestModSecurityDetector:
    def setup_method(self):
        self.det = ModSecurityDetector()

    def test_server_header(self):
        r = _mock_response({"server": "Apache/2.4 (mod_security)"})
        result = self.det.score(r, "")
        assert result.vendor == WAFVendor.MODSECURITY
        assert result.confidence >= CONFIDENCE_THRESHOLD

    def test_body_pattern(self):
        body = "This error was generated by Mod_Security. Your request was blocked."
        r = _mock_response({}, 406, body)
        result = self.det.score(r, body)
        assert result.confidence >= CONFIDENCE_THRESHOLD

    def test_406_status_alone_low_confidence(self):
        r = _mock_response({}, 406, "")
        result = self.det.score(r, "")
        # Status alone should give small score, not meet threshold
        assert result.confidence < CONFIDENCE_THRESHOLD


# ── AWS WAF ───────────────────────────────────────────────────────────────────

class TestAWSWAFDetector:
    def setup_method(self):
        self.det = AWSWAFDetector()

    def test_trace_id(self):
        r = _mock_response({"x-amzn-trace-id": "Root=1-abc-xyz"})
        result = self.det.score(r, "")
        assert result.vendor == WAFVendor.AWS_WAF
        assert result.confidence >= 0.20

    def test_body_pattern(self):
        body = "Request blocked by AWS WAF"
        r = _mock_response({}, 403, body)
        result = self.det.score(r, body)
        assert result.confidence >= CONFIDENCE_THRESHOLD


# ── Imperva ───────────────────────────────────────────────────────────────────

class TestImpervaDetector:
    def setup_method(self):
        self.det = ImpervaDetector()

    def test_x_iinfo_header(self):
        r = _mock_response({"x-iinfo": "9-12345-0 NNNN"})
        result = self.det.score(r, "")
        assert result.vendor == WAFVendor.IMPERVA
        assert result.confidence >= CONFIDENCE_THRESHOLD

    def test_incap_cookie(self):
        r = _mock_response({}, cookies={"incap_ses_123_456": "abc"})
        result = self.det.score(r, "")
        assert result.confidence >= 0.40

    def test_body_incapsula(self):
        body = "Request unsuccessful. Incapsula incident ID: 1234567890"
        r = _mock_response({}, 403, body)
        result = self.det.score(r, body)
        assert result.confidence >= CONFIDENCE_THRESHOLD


# ── F5 BIG-IP ─────────────────────────────────────────────────────────────────

class TestF5BigIPDetector:
    def setup_method(self):
        self.det = F5BigIPDetector()

    def test_x_wa_info(self):
        r = _mock_response({"x-wa-info": "XXXXXX"})
        result = self.det.score(r, "")
        assert result.vendor == WAFVendor.F5_BIGIP
        assert result.confidence >= CONFIDENCE_THRESHOLD

    def test_ts_cookie(self):
        r = _mock_response({}, cookies={"TSe1a2b3c4": "abc"})
        result = self.det.score(r, "")
        assert result.confidence >= 0.30

    def test_body_support_id(self):
        body = "The requested URL was rejected. Please consult with your administrator. Your support ID is: 12345678901234567890"
        r = _mock_response({}, 403, body)
        result = self.det.score(r, body)
        assert result.confidence >= CONFIDENCE_THRESHOLD


# ── Orchestrator ──────────────────────────────────────────────────────────────

class TestOrchestrator:
    def setup_method(self):
        self.orch = FingerprintOrchestrator()

    def test_cloudflare_wins_with_cf_ray(self):
        r = _mock_response({"cf-ray": "8abc-LHR", "server": "cloudflare"})
        result = self.orch.identify(r)
        assert result.vendor == WAFVendor.CLOUDFLARE

    def test_unknown_returns_none(self):
        r = _mock_response({"server": "nginx", "x-custom": "foo"})
        result = self.orch.identify(r)
        assert result.vendor == WAFVendor.NONE

    def test_identify_all_returns_list(self):
        r = _mock_response({"cf-ray": "abc", "server": "cloudflare"})
        results = self.orch.identify_all(r)
        assert isinstance(results, list)
        assert len(results) >= 1
        assert results[0].vendor == WAFVendor.CLOUDFLARE

    def test_identify_all_empty_for_no_signals(self):
        r = _mock_response({"content-type": "text/html"})
        results = self.orch.identify_all(r)
        assert results == []
